#!/bin/sh
set -e

if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ]; then
    if command -v systemctl >/dev/null 2>&1; then
        systemctl --global disable odoo-companion.service >/dev/null 2>&1 || true
    fi
fi

#DEBHELPER#

exit 0
